"""Build an evidence-only extension and close the gate; never run classifiers."""
import json
from datetime import datetime, timezone
from pathlib import Path
import pandas as pd
from bhns.data.state_validation import sha256, verify_protected, contained
from bhns.data.state_extension import validate_extension, merge_catalogues, source_gate, validate_chronology
R=Path(__file__).resolve().parents[1]
D=R/'data/state_extension'; O=R/'results/state_extension'; P=R/'reports/state_extension'; C=R/'configs/state_extension'
# Decisions concern the frozen processed targets, not all epochs of these systems.
NOTES={
'igr_j00291_5934': ('linares2007;falanga2005;shaw2005', 'Linares Table 1 identifies 90052-03-01-00 (A1), 90425-01-01-13 (A2), and 90425-01-02-14 (B). Sections 4.1, 4.2 and 5.1 describe the hard exceptional-island state. Falanga independently describes thermal Comptonization. Admit A1/A2; the B observation is retained provisionally because the paper explicitly warns that the foreground intermediate polar significantly affects the late colors. The 2008 pointing is outside these studies. The rounded Table 1 dates do not exactly reproduce archive start times: exact identifiers, not rounded dates, provide the native-state join.'),
'sax_j1808_4_3658': ('bult2015;ibragimov2009', 'Bult Table 1 explicitly lists selected 2002 intervals 7 and 19 (IS), 2005 interval 11 (IS), 2008 interval 3 (IS), and 2011 interval 9 (EIS); published prefixes B/C/D/E are expanded exactly. Sections 2 and 4 describe averaging only similar power spectra. Only the two 2002 pointings also lie wholly within Ibragimov Table 1 slow-decay interval MJD 52564.25–52574.29. Its Sections 3.1–3.2 give a hot Comptonized continuum with a surface blackbody; the thermal surface component does not imply taxonomy equivalence. Retain IS/EIS native labels for later outbursts, without extrapolating the 2002 spectral mapping. Exclude November 2002 flaring-tail pointings: no secure full-pointing native label from the table, and strong flaring.'),
'ks_1731_260': ('muno2000;chen2014;barret2000;gladstone2007', 'The retained Muno native island assignment for 30061-01-02-06 remains unchanged. Barret Section 3.1 covers 1997 October 28–30 in a banana spectrum, not this 1998 pointing. Gladstone includes KS 1731-260 in an intrinsic-color population study, but no recovered per-ObsID component/state join demonstrates that the Muno island selection meets the common spectral definition. A general island=hard caption is insufficient for the required evidence-specific mapping. Later 2000–2001 targets remain without a secure interval join.'),
'4u_0614_09': ('ford1997;vanstraaten2000;gladstone2007', 'Van Straaten Table 1 contains April 22 1996 segments and a continuous Sa coordinate. It does not give a uniquely recovered hard-state boundary covering the full frozen 10095-01-01-00 spectrum. The earlier Ford/Mendez follow-up observation dates differ. No universal Sa threshold is invented; native color/timing context remains insufficient. Gladstone source-level intrinsic colors do not supply a frozen-ObsID state join.'),
'4u_1728_34': ('tarana2011;migliari2003', 'Tarana Sections 2–3 use HID boxes 1–3 for hard spectra and 4–6 for soft spectra, with data aggregated across monitoring periods. RXTE dates overlap parts of our 2006–2007 coverage, but a box-to-ObsID or full-GTI membership table was not recovered. No state is read from a nearby plotted point or interpolated across gaps. Migliari simultaneous radio/X-ray epochs do not establish a full-pointing mapping for our selected dates. Hard states exist in this source; their existence alone cannot label our spectra.'),
'4u_1702_429': ('markwardt1999', 'Markwardt discusses July 19, 21, 26 and 30 1997; selected 20084-02-01-00 is July 19. The discussion explicitly questions whether the observations reached island state. Timing evolution and a possible intermediate banana identification do not justify a secure hard assignment. Other selected epochs lack exact recovered evidence.'),
'4u_1705_44': ('chen2014;egron2013', 'The retained Church/Chen campaign P93060 is September–November 2007, whereas our selected later P93060 pointings are in 2008. Egron reports hard/soft spectral fits, but the manuscript PDF and publisher text were inaccessible (HTTP 406/403); only the primary abstract could be screened. No exact selected ObsID/state join was extracted. Burst detections in the selected April 2002 pointing are not whole-ObsID state evidence. Access limitations remain explicit.'),
'4u_1636_536': ('belloni2007;altamirano2008;disalvo2003', 'Di Salvo studies lower/upper banana behavior. Table 1 includes 30053-02-01-000 on 1998 February 24; the frozen identifier is 30053-02-01-00. Trailing-zero identifiers are not silently collapsed. Later QPO-track selections are not an extracted full-GTI state join. No source-independent hard mapping or new primary assignment is admitted.'),
'hete_j1900_1_2455': ('patruno2017;watts2009;papitto2013', 'Patruno Table 1 groups are timing-fit groups, not a state-per-ObsID table. Explicit island examples 92049-01-44-00 and 91015-01-06-02 are not selected. Watts studies the 2009 April 2 burst, not our July 11 observation. Papitto Section 2.2 explicitly identifies hard/Comptonized 96030-01-34-00 on 2011 September 20; our selected pointing is 96030-01-32-00 on September 6. No two-week extrapolation or pulsar-type-to-state assumption is allowed.'),
'aql_x_1': ('zhang1998;cui1998;rodriguez2006;chen2013aql', 'Rodriguez Table 1 hard-state RXTE observations are P91414 in May 2005 (MJD 53493.77 onward), not selected P91028 on April 4. Chen Table 1 explicitly labels bursts in selected 70069-03-02-03 as soft and 93076-01-09-00 as hard, but the table states state when bursts occurred. Its burst/preburst analysis does not establish the state of all GTIs in the frozen spectra. Retain these as partial-interval provisional evidence, not whole-ObsID assignments. No actual transition is asserted merely because coverage is partial.'),
'slx_1735_269': ('wijnands1999slx;barret2000;chen2014', 'The earlier February–May 1997 timing paper provides tentative native-state interpretation, retained provisionally. Barret Section 3.1 establishes a hard Comptonized spectrum on 1997 October 10–12, which is outside the selected February/May pointings. The 2003 P80138 campaign overlaps October 6 but crosses the atoll track without a recovered exact box/GTI join. Neither campaign-average spectra nor adjacent dates upgrade a tentative label.'),
'1a_1744_361': ('bhattacharyya2006', 'The published 2003 banana and 2004 atoll-horizontal/low-hard assignments remain in the original catalogue. The hard 2004 pointings are not in the frozen expanded cohort. The first 2005 observation may be transitional; our selected July 19 pointing is later. No blanket outburst-state extension is made. More archival spectra of an already represented state do not count without the frozen processed support.'),
'sax_j1750_8_2900': ('kaaret2002', 'Kaaret 2002 is the relevant 2001 RXTE outburst study; retained retrieval did not yield a secure full-ObsID state table for selected 60035-01-01-00. Later search results describe 2008 outburst/burst activity without an extracted mapping to the selected April observation. Record unavailable/insufficient evidence, not absence of physical hard states.'),
'mxb_1658_298': ('sharma2018', 'Sharma examines the 2015–2017 outburst after RXTE operations. Earlier 1999–2001 burst, eclipse and dipping context does not provide a recovered selected-ObsID hard/soft state join. Inclination or source type is not a state criterion.'),
'sax_j1806_5_2215': ('', 'The targeted query and retained ATels locate the 2011 outburst, thermonuclear bursts, Swift spectrum and INTEGRAL hard-X-ray detection. These are activity/continuum leads without a secure selected RXTE full-ObsID state interval. No new usable label; no primary full-text state paper was recovered for this target.'),
'4u_1735_444': ('lei2013', 'Lei HID/CCD regions establish banana context for a subset of a 1996–1999 study, including a provisional upper-banana assignment already retained outside the expanded subset. No independently verified hard interval or precise full-pointing region membership was recovered for the selected targets.'),
'4u_1254_69': ('', 'Smale 2002 and the later published spectral work are candidate studies, but selected processed pointings begin in 2004. Search/retained-review screening did not recover a matching full-ObsID state table. Generic banana-source descriptions cannot label the selected observations or manufacture hard support.'),
'4u_1746_37': ('jonker2000', 'Jonker studies 1996/1998 observations; the frozen processed sample begins in 2002. The Maccarone 2003 lead refers to P10112/P30701/P60044 rather than the selected P70050 and later observations. No hard-state extrapolation to later years is made.'),
'cyg_x_2': ('wijnands1999cyg', 'The retained Wijnands study concerns October 1996 and September 1997, not the selected July 1997 pointing. Z-branch terminology is kept distinct from common hard/soft spectral regimes. No secure new selected full-ObsID branch join recovered.'),
'ser_x_1': ('oosterbroek2001;migliari2004', 'The existing evidence-specific soft campaign already contributes one NS source and is retained. The Masetti 2004 lead concerns a different 2003 epoch; no new independent source is gained by adding Ser X-1 spectra. No hard-supported processed observation recovered.')}

def main():
 verify_protected(R,json.loads((O/'protected_artifact_manifest.json').read_text()))
 plan=json.loads((C/'search_plan_frozen.json').read_text())
 assert sha256(C/'search_plan_frozen.json')==(C/'search_plan_frozen.sha256').read_text().strip()
 assert sha256(D/'ns_candidate_priority.csv')==plan['candidate_priority_sha256']
 old=pd.read_csv(R/'data/state_validation/obsid_state_catalogue.csv').fillna('')
 targets=old[old.in_expanded & old.source_id.isin(plan['ordered_target_sources'])]
 refs=json.loads((R/'data/state_validation/literature/curated_references.json').read_text())
 for f in sorted((D/'literature').glob('retrievals_*.json')):
  for r in json.loads(f.read_text()):
   if r.get('status')=='retrieved' or r['reference_id'] not in refs:refs[r['reference_id']]=r
 refs['papitto2013']=dict(reference_id='papitto2013',url='https://academic.oup.com/mnras/article/429/4/3411/1018680',status='publisher_full_text_screen',title='The accretion flow to the intermittent accreting millisecond pulsar, HETE J1900.1−2455, as observed by XMM–Newton and RXTE')
 rows=[]
 for r in targets.to_dict('records'):
  keys,note=NOTES[r['source_id']]
  e={k:r[k] for k in ['rxte_obsid','source_id','canonical_source','class_label','observation_start','observation_end','start_mjd','end_mjd']}
  e.update(native_state_label='UNCLASSIFIED',common_regime='UNMAPPED',evidence_level='UNRESOLVED',evidence_method='bounded_literature_screen_no_secure_new_join',reference_id=keys,reference_url_or_identifier=';'.join(refs[k].get('url','') for k in keys.split(';') if k),direct_obsid_match=False,date_match=False,gti_match=False,whole_observation_supported=False,ambiguous=False,conflicted=False,eligible_for_confirmatory=False,notes=note,mapping_rule_id='',regime_evidence_level='UNRESOLVED')
  obs=r['rxte_obsid']
  if obs in {'90052-03-01-00','90425-01-01-13'}:
   e.update(native_state_label='NS_EXCEPTIONAL_ISLAND',common_regime='HARD_DOMINATED',evidence_level='DIRECT',evidence_method='exact_ObsID_in_Linares_Table1_A1_A2_and_sections4_5',direct_obsid_match=True,whole_observation_supported=True,mapping_rule_id='IGR_2004_A1_A2',regime_evidence_level='DIRECT')
  if obs=='90425-01-02-14':
   e.update(native_state_label='NS_EXCEPTIONAL_ISLAND',evidence_level='PROVISIONAL',direct_obsid_match=True,ambiguous=True,evidence_method='Table1_B_late_colors_contaminated_not_primary_regime_evidence')
  if obs in {'70080-01-02-03','70080-01-03-12','91056-01-03-09','93027-01-02-00','96027-01-02-07'}:
   e.update(native_state_label='NS_ATOLL_EXTREME_ISLAND' if obs=='96027-01-02-07' else 'NS_ATOLL_ISLAND',evidence_level='DIRECT',evidence_method='Bult_Table1_exact_ObsID_prefix_expansion',direct_obsid_match=True,whole_observation_supported=True)
   if obs.startswith('70080'):
    assert contained(r['start_mjd'],r['end_mjd'],52564.25,52574.29)
    e.update(common_regime='HARD_DOMINATED',date_match=True,mapping_rule_id='SAX1808_2002_SD',regime_evidence_level='STRONG',evidence_time_start=52564.25,evidence_time_end=52574.29)
  if obs in {'70069-03-02-03','93076-01-09-00'}:
   e.update(native_state_label='MIXED_OR_TRANSITION',evidence_level='PROVISIONAL',direct_obsid_match=True,ambiguous=True,evidence_method='burst_epoch_only_full_GTI_state_unverified',notes=note+' MIXED_OR_TRANSITION is the exclusion category for an unverified whole-ObsID state; the published burst state is '+('SOFT' if obs.startswith('70069') else 'HARD')+'.')
  e['eligible_for_confirmatory']=(e['evidence_level'] in {'DIRECT','STRONG'} and e['whole_observation_supported'] and not e['ambiguous'] and e['common_regime']!='UNMAPPED')
  rows.append(e)
 ext=pd.DataFrame(rows);validate_extension(ext)
 # Freeze evidence-specific mappings before computing the gate; never broaden from results.
 mapping_path=C/'state_regime_mapping_v2_frozen.json'
 mapping=dict(version='STATE_REGIME_MAPPING_V2_EXTENSION',frozen_utc=datetime.now(timezone.utc).isoformat(),parent_path='configs/state_regime_mapping.yaml',parent_sha256=sha256(R/'configs/state_regime_mapping.yaml'),physical_equivalence_claim=False,automatic_native_to_common_mapping=False,rules={
 'IGR_2004_A1_A2':dict(source_id='igr_j00291_5934',obsids=['90052-03-01-00','90425-01-01-13'],native='exceptional island; publication wording preserved',common='HARD_DOMINATED',evidence='Linares Table 1 A1/A2 and sections 4.1/4.2/5.1 explicitly hard; corroborating thermal Comptonization in Falanga. Late contaminated B/C excluded.'),
 'SAX1808_2002_SD':dict(source_id='sax_j1808_4_3658',obsids=['70080-01-02-03','70080-01-03-12'],native='island in Bult Table 1; slow decay is a separate outburst phase',common='HARD_DOMINATED',evidence='Bult exact native IS plus full-span containment within Ibragimov Table 1 SD 52564.25–52574.29, whose spectral model has hot Comptonization and surface blackbody; sections 3.1–3.2. This is a broad hard/Comptonized observable restriction, not equality of NS/BH accretion physics.')})
 if mapping_path.exists():
  assert sha256(mapping_path)==mapping_path.with_suffix('.sha256').read_text().strip()
  saved=json.loads(mapping_path.read_text());assert saved['rules']==mapping['rules'];mapping=saved
 else:
  mapping_path.write_text(json.dumps(mapping,indent=2));mapping_path.with_suffix('.sha256').write_text(sha256(mapping_path)+'\n')
 ext.to_csv(D/'obsid_state_catalogue_extension.csv',index=False)
 merged=merge_catalogues(old,ext);merged.to_csv(D/'obsid_state_catalogue_merged.csv',index=False)
 cohort=merged[merged.in_expanded];gate=source_gate(cohort);gate.to_csv(O/'regime_feasibility.csv',index=False)
 if gate.PASS.any():raise RuntimeError('PASS: stop evidence builder and preregister Branch A before any model fitting')
 reviewed=[]
 for sid in plan['ordered_target_sources']:
  for key in NOTES[sid][0].split(';'):
   if not key:continue
   ref=refs[key];local=ref.get('path','');full=local and (R/local).exists()
   origin='new_retrieval' if local.startswith('data/state_extension/') else 'retained_review_rechecked'
   if key=='papitto2013':origin='new_publisher_full_text'
   if key=='egron2013':origin='new_abstract_only_access_blocked'
   reviewed.append(dict(source_id=sid,reference_id=key,url=ref.get('url',''),screen_scope=origin,status=ref.get('status',''),local_path=local,sha256=sha256(R/local) if full else '',locator_and_decision=NOTES[sid][1]))
 pd.DataFrame(reviewed).to_csv(D/'manuscript_screening_registry.csv',index=False)
 (D/'reviewed_references.json').write_text(json.dumps({r['reference_id']:refs[r['reference_id']] for r in reviewed},indent=2))
 outcomes=[];(P/'sources').mkdir(exist_ok=True)
 for sid in plan['ordered_target_sources']:
  g=ext[ext.source_id.eq(sid)];m=cohort[cohort.source_id.eq(sid)];keys,note=NOTES[sid]
  n=int(g.eligible_for_confirmatory.sum());name=g.canonical_source.iloc[0]
  outcomes.append(dict(source_id=sid,canonical_source=name,search_status='BOUNDED_REVIEW_COMPLETE',reviewed_obsids=len(g),new_DIRECT=int(g.evidence_level.eq('DIRECT').sum()),new_STRONG=int(g.evidence_level.eq('STRONG').sum()),new_common_regime_observations=n,independent_hard_source_gain=int(n>0),decision='NEW_HARD_SUPPORT' if n else 'NO_NEW_HARD_SUPPORT',reason=note))
  links='\n'.join('- ['+key+']('+refs[key].get('url','')+') — '+next(x['screen_scope'] for x in reviewed if x['source_id']==sid and x['reference_id']==key) for key in keys.split(';') if key) or 'No full-text state manuscript recovered; discovery leads are retained in the query logs and prior dossier.'
  cols=['rxte_obsid','observation_start','observation_end','native_state_label','evidence_level','common_regime','eligible_for_confirmatory']
  text=f'# {name}: targeted NS evidence review\n\nSource class: independently verified NS in the frozen cohort; native taxonomy is study-specific. Processed targets: {len(g)}. This review does not classify all archival observations of the source.\n\n## Manuscripts and review scope\n\n{links}\n\n## Evidence, temporal correspondence, and conflicts\n\n{note}\n\nNo competing admitted native-state assignment was found. Discrepant or incomplete coverage is described above; this is not a claim of universal literature agreement. Full GTI lists were not newly extracted: exact full-pointing native labels or conservative full archive-span containment are required. The field gti_match remains false where no explicit published GTI boundary was joined.\n\n## All selected ObsIDs and dates\n\n{g[cols].to_markdown(index=False)}\n\n## Final decision\n\nNew observations usable in a common regime: {n}; independent hard-regime source gain: {int(n>0)}. Other observations remain unavailable for common matching; original valid labels remain active in the derived catalogue. No source class, proxy value, or classifier prediction was used to assign a state.\n'
  (P/'sources'/f'{sid}.md').write_text(text)
 pd.DataFrame(outcomes).to_csv(D/'ns_candidate_outcomes.csv',index=False)
 confidence=cohort.groupby(['class_label','state_confidence']).agg(observations=('rxte_obsid','size'),sources=('source_id','nunique')).reset_index();confidence.to_csv(O/'evidence_coverage.csv',index=False)
 regime_levels=[]
 for regime,g in cohort.groupby('common_regime'):
  rec={'common_regime':regime}
  for level in ['DIRECT','STRONG','PROVISIONAL','UNRESOLVED','CONFLICTED']:
   rec[level+'_sources']=g[g.state_confidence.eq(level)].source_id.nunique()
  rec['ambiguous_sources']=g[g.ambiguous].source_id.nunique()
  regime_levels.append(rec)
 regime_levels=pd.DataFrame(regime_levels);regime_levels.to_csv(O/'regime_evidence_levels.csv',index=False)
 # Eligibility-gate and missingness units are explicit; a source can occupy multiple evidence categories.
 queries=sum(len(json.loads(p.read_text())['queries']) for p in D.glob('search_batch_*.json'))
 status=dict(branch='B',feasibility='FAIL',state_question='STATE_CONTROL_NOT_FEASIBLE_WITH_AVAILABLE_EVIDENCE',verdict='STATE_EXTENSION_CLOSED_INFEASIBLE',publication_readiness='D',decided_utc=datetime.now(timezone.utc).isoformat(),candidate_universe=22,targets_searched=20,discovery_and_followup_queries=queries,processed_target_obsids=len(ext),papers_screened=len({x['reference_id'] for x in reviewed}),new_native_DIRECT=int(ext.evidence_level.eq('DIRECT').sum()),new_native_STRONG=int(ext.evidence_level.eq('STRONG').sum()),new_common_regime_observations=int(ext.eligible_for_confirmatory.sum()),new_common_regime_sources=int(ext[ext.eligible_for_confirmatory].source_id.nunique()),ml_runs=0,cohort_created=False,minimum_sources_per_class=5,regimes=gate.to_dict('records'),mapping_sha256=sha256(mapping_path),extension_sha256=sha256(D/'obsid_state_catalogue_extension.csv'),merged_sha256=sha256(D/'obsid_state_catalogue_merged.csv'),search_plan_sha256=sha256(C/'search_plan_frozen.json'))
 validate_chronology(plan,mapping,status);(O/'stage_status.json').write_text(json.dumps(status,indent=2))
 (P/'state_extension_feasibility.md').write_text('# State-extension feasibility\n\n**FAIL.** Count physical systems in the frozen expanded HEASoft cohort, using only DIRECT/STRONG evidence and a justified common regime. Minimum remains five systems per class. No classifier performance was consulted.\n\n'+gate.to_markdown(index=False)+'\n\nEvidence-level coverage (categories can overlap at source level; unresolved observations have no defensible common regime and are not assigned to one for counting):\n\n'+confidence.to_markdown(index=False)+'\n\nHard NS support increases from 2 to 4; the remaining deficit is **one independent NS system**. Soft support remains 2 BH/1 NS, with deficits of 3 BH and 4 NS. DIRECT/STRONG columns count native evidence; SAX J1808 common-regime mapping additionally uses STRONG spectral-interval evidence.\n\nThe merged catalogue retains all 880 original rows and all original fields under original_ prefixes. The extension reviews only processed target ObsIDs; rows are not extra independent spectra. Native-only labels and partial burst evidence do not enter common-regime support.\n')
 (P/'state_extension_closure.md').write_text('# Formal closure of the bounded state extension\n\n**STATE_EXTENSION_CLOSED_INFEASIBLE**\n\n**STATE_CONTROL_NOT_FEASIBLE_WITH_AVAILABLE_EVIDENCE**\n\n'+f'The predeclared universe contained 22 NS systems, of which 20 lacked hard-regime support and were searched with {queries} targeted discovery/follow-up queries. We screened {status["papers_screened"]} distinct manuscripts/primary publication records, including retained reviews rechecked, newly retrieved full texts, a publisher full text, and an abstract with blocked full-text access. Screening depth and access failures are explicit in manuscript_screening_registry.csv. We reviewed all {len(ext)} frozen processed target ObsIDs; the two already contributing NS systems were retained without searching for additional observations.\n\n'+f'New native labels: {status["new_native_DIRECT"]} DIRECT and {status["new_native_STRONG"]} STRONG. Four new observations in two independent NS systems qualify for the common hard regime: IGR J00291+5934 and SAX J1808.4−3658. Three additional SAX J1808 native labels remain unmapped. Late IGR color contamination and two Aql X-1 burst-only matches remain provisional.\n\n'+gate.to_markdown(index=False)+'\n\nHard support is 6 BH/4 NS, one NS short of the gate. Soft support is 2 BH/1 NS, short by three BH and four NS. Source-specific dossiers record why each remaining target could not be used: nonoverlapping epochs, missing state-to-ObsID/GTI correspondence, tentative taxonomy, mixed/partial intervals, inadequate physical mapping, or inaccessible full text. No claim is made that no further evidence exists anywhere in the archive. This closure applies to the declared processed cohort and bounded available-evidence review; no new source reduction was part of the frozen search plan.\n\n> No valid state-controlled classifier was trained because the preregistered source-diversity criterion was not satisfied.\n\nState-controlled cohort: **NOT CREATED**. State-controlled ML and comparator: **NOT RUN BY DESIGN**. No new ML protocol or empty performance table is presented as an executed experiment. A prospective future data expansion would need a separate protocol; it is not the next action for this project.\n\nReadiness **D**: major planned analysis is complete for the bounded paper, including this infeasibility outcome. Physical-state independence remains unresolved and must not enter the abstract as an achieved result. The next action is manuscript integration and journal preparation.\n')
 (P/'reproduced_state_diagnostics.md').write_text('# Source-specific diagnostic assessment\n\nNo new hardness/color diagnostic was reproduced. Tarana HID boxes, van Straaten Sa tracks, and Gladstone intrinsic colors require an exact source-specific temporal selection and/or absorption-corrected model fluxes that are not the frozen 43-bin detector rates. No universal threshold, visual interpolation, fitted cluster, or BH/NS probability was substituted. Exact published ObsIDs and one bounded spectral interval supplied the admitted evidence.\n')
 with (P/'state_extension_feasibility.md').open('a') as f:
  f.write('\n## Evidence levels by assigned regime\n\n'+regime_levels.to_markdown(index=False)+'\n\nThe PROVISIONAL and UNRESOLVED rows remain UNMAPPED; zeros in hard/soft columns do not imply complete state coverage. An unresolved observation cannot legitimately be placed in either physical regime for counting. Source counts overlap across observations, levels and regimes. Evidence-level coverage includes ambiguous rows; confirmatory counts in the first table exclude them.\n')
 (P/'search_scope_and_mapping.md').write_text('# Search scope and mapping audit\n\nThe candidate priority CSV and search plan were hashed before the 32 planned queries (20 initial and 12 focused follow-ups). All 12 high-priority and 8 secondary targets were screened. Reference-roster context was retained, but no new source/provenance reduction was authorized by this stage\'s frozen scope. Discovery outputs are search_batch_01–08.json; a stray author-link navigation during DOI retrieval returned an unrelated author listing and supplied no evidence. Known-paper DOI/ADS/OpenAlex navigation was used only to retrieve already identified publications, not to expand discovery.\n\nEleven new PDFs were retrieved (below the cap of 24); Papitto was read through the publisher full text. Egron full text remained inaccessible after arXiv and publisher attempts; its abstract supplied no assignment. Bult was recovered via its exact DOI metadata and arXiv 1505.00596. Retrieval retries are retained separately and are not additional manuscripts. Other registry entries explicitly reuse retained primary-paper reviews.\n\nMapping V2 retains the V1 definition and adds two source-and-observation-specific rules. NS island is not mapped automatically. The IGR rule uses explicit published hard exceptional-island behavior; the SAX rule combines exact native IS labels with contemporaneous hard Comptonization. Native IS/EIS labels in later SAX outbursts remain unmapped. A surface blackbody remains part of the SAX spectrum; the common category does not assert identical spectral decomposition or accretion physics.\n\nRendered Linares Table 1, Bult Table 1 (including prefix footnote), and Ibragimov Table 1 were visually checked. The two 2002 SAX whole-observation spans pass the 120-second guard within the published slow-decay phase. Exact-ObsID evidence is distinct from a recovered published GTI list, which was not available. The original state mapping and catalogue remain byte-for-byte unchanged.\n')
 print(json.dumps(status,indent=2))
if __name__=='__main__':main()
