"""Declare the additive evidence-recovery scope before new literature searching."""
import json
from datetime import datetime,timezone
from pathlib import Path
import pandas as pd
from bhns.data.state_validation import sha256,verify_protected,usable_states
R=Path(__file__).resolve().parents[1]
def main():
 verify_protected(R,json.loads((R/'results/state_extension/protected_artifact_manifest.json').read_text()))
 if (R/'configs/state_extension/search_plan_frozen.json').exists():raise ValueError('Search plan already frozen')
 cat=pd.read_csv(R/'data/state_validation/obsid_state_catalogue.csv');ns=cat[cat.class_label.eq('NS')];expanded=ns[ns.in_expanded]
 priority=['igr_j00291_5934','sax_j1808_4_3658','ks_1731_260','4u_0614_09','4u_1728_34','4u_1702_429','4u_1705_44','4u_1636_536','hete_j1900_1_2455','aql_x_1','slx_1735_269','1a_1744_361','sax_j1750_8_2900','mxb_1658_298','sax_j1806_5_2215','4u_1735_444','4u_1254_69','4u_1746_37','cyg_x_2','ser_x_1']
 rows=[]
 for sid,g in expanded.groupby('source_id'):
  existing=sid not in priority;n=priority.index(sid)+1 if not existing else 0
  reason=('Already contributes to hard support; additional spectra cannot add an independent system.' if existing else 'High priority: published RXTE timing/spectral campaigns or native labels may yield an exact state/regime link.' if n<=12 else 'Secondary priority: date-specific state papers screened; soft/Z/ambiguous taxonomy may not yield hard support.')
  rows.append(dict(source_id=sid,canonical_source=g.canonical_source.iloc[0],currently_in_cohort=True,rxte_observations_available=len(g),considered_ObsIDs=int(ns.source_id.eq(sid).sum()),current_state_evidence=';'.join(sorted(set(g.state_confidence))),candidate_common_regime='HARD_DOMINATED',priority=n,reason=reason,search_status='EXISTING_HARD_SUPPORT' if existing else 'PENDING',search_tier='existing' if existing else 'high' if n<=12 else 'secondary'))
 pd.DataFrame(rows).sort_values('priority').to_csv(R/'data/state_extension/ns_candidate_priority.csv',index=False)
 expanded[['rxte_obsid','source_id','canonical_source','observation_start','observation_end','native_state_label','common_regime','state_confidence']].to_csv(R/'data/state_extension/ns_processed_observation_targets.csv',index=False)
 plan=dict(frozen_utc=datetime.now(timezone.utc).isoformat(),candidate_universe='22 NS systems in frozen expanded HEASoft cohort; target the 20 without admissible hard support',ordered_target_sources=priority,high_priority_sources=priority[:12],selection_basis='prior literature dossiers and availability of processed observations; no classifier scores consulted',primary_support='Count only matching frozen expanded-cohort observations after evidence validation; archival-only gains reported separately',search_bound='One targeted discovery query for each of 20 targets; at most 12 focused follow-up queries, at most 24 newly retrieved primary manuscripts, plus re-screening retained relevant manuscripts. Complete all high-priority screens and document exact temporal/ObsID/GTI linkage. No further source expansion or new reduction in this bounded stage.',source_expansion='Existing cohort is priority 1. The reference roster is inspected for context, but no unverified identities or new source/provenance reduction is added in this bounded round.',evidence=['DIRECT','STRONG'],excluded=['PROVISIONAL','UNRESOLVED','CONFLICTED','MIXED_OR_TRANSITION'],minimum_independent_sources_per_class=5,common_mapping='Reuse existing HARD_DOMINATED definition: explicit source-specific published hard/Comptonized spectral interpretation; native island never sufficient alone.',date_matching='Whole frozen ObsID time span within published interval; 120-second conservative boundary guard. Partial or ambiguous GTI matches excluded.',branch_A='Freeze new inclusion/mapping/protocol before any ML fit; original simple models and source-isolated nested evaluation.',branch_B='No classifier; formally close available-evidence state control and complete manuscript drafts.',proxy_warning='Do not infer physical state from previous proxy values or classifier predictions.',candidate_priority_sha256=sha256(R/'data/state_extension/ns_candidate_priority.csv'),previous_mapping_sha256=sha256(R/'configs/state_regime_mapping.yaml'))
 p=R/'configs/state_extension/search_plan_frozen.json';p.write_text(json.dumps(plan,indent=2));p.with_suffix('.sha256').write_text(sha256(p)+'\n')
 m=R/'manuscript';m.mkdir(exist_ok=True)
 outline=['Introduction','Related work','Scientific question','RXTE/PCA dataset reconstruction','Source/label provenance','Spectral processing','Machine-learning methodology','Leakage-safe evaluation','Primary results','Source-fingerprint controls','HEASoft/CALDB validation','Detector-confounder analysis','Spectral-state audit','State-controlled extension or feasibility limitation','Discussion','Limitations','Conclusions','Reproducibility']
 (m/'outline.md').write_text('# Manuscript outline\n\nWorking title: Source-independent compact-object discrimination in RXTE/PCA spectra: provenance, instrumental validation, and limits of state control\n\nCentral claim: useful spectral ranking in the selected RXTE cohort survives withholding physical systems and independent HEASoft/CALDB processing and detector-support restrictions. Physical-state independence remains unestablished pending this bounded extension.\n\n'+'\n'.join(f'{i}. {s}' for i,s in enumerate(outline,1))+'\n\nResults progression: R1 observation split; R2 unseen sources; R3 source-label null; R4 independent processing; R5 detector support; R6 source expansion; R7 state catalogue/proxies; R8 extension outcome. No numerical result may be replaced by a draft estimate.\n')
 print('Frozen candidate universe:',len(rows),'NS systems;',len(priority),'search targets.')
if __name__=='__main__':main()
